- name: Add host to Inventory and update ssh keys
  hosts: "{{ server }}"
  become: true
  vars:
    server: "{{ server }}"
  tasks:
  - name: Find line index matching pattern
    command: awk '/^\\[ec2_list\\]$/{ print NR; exit }' /etc/ansible/hosts
    register: line_number
  - name: Add host to Inventory
    lineinfile:
      path: /etc/ansible/hosts
      regexp: '^\\[ec2_list\\]$'
      line: "{{ new_public_ip }}"
      insertafter: "{{ line_number.stdout }}"
- name: Create new group on the new host
  hosts: "{{ new_public_ip }}"
  become: true
  become_user: ec2-user
  vars:
    username: hari
    groupname: hari
    home_directory: /home/hari
  tasks:
  - name: Create group
    group:
      name: "{{ groupname }}"
      state: present
  - name: Create user
    user:
      name: "{{ username }}"
      group: "{{ groupname }}"
      createhome: yes
      home: "{{ home_directory }}"
      shell: /bin/bash
      state: present






