- name: Add host to Inventory and update ssh keys
  hosts: "{{ server }}"
  become: true
  vars:
    server: "{{ server }}"
    new_public_ip: "{{ new_public_ip }}"
  tasks:
  - name: Add host to Inventory
    lineinfile:
      path: /etc/ansible/hosts
      line: "{{ new_public_ip }}"
      insertafter: "{{ '^\\[ec2_list\\]$' }}"






