- name: Add host to Inventory and update ssh keys
  hosts: "{{ server }}"
  become: true
  vars:
    server: "{{ server }}"
    new_public_ip: "{{ new_public_ip }}"
    new_host_group: "ec2_list"
    username: myuser
    groupname: mygroup
    home_directory: /home/myuser
  tasks:
  - name: Add host to Inventory
    add_host:
      name: "{{ new_public_ip }}"
      group: "{{ new_host_group }}"
      ansible_host: "{{ new_public_ip }}"
  - name: Copy id_rsa.pub to remote host
    become: true
    become_user: ec2-user
    copy:
      src: /home/nani/.ssh/id_rsa.pub
      dest: /home/nani/.ssh/authorized_keys
      mode: 0600
    delegate_to: "{{ new_public_ip }}"
  - name: Create group
    group:
      name: "{{ groupname }}"
      state: present
    delegate_to: "{{ new_public_ip }}"
  - name: Create user
    user:
      name: "{{ username }}"
      group: "{{ groupname }}"
      createhome: yes
      home: "{{ home_directory }}"
      shell: /bin/bash
      state: present
    delegate_to: "{{ new_public_ip }}"


