- name: Add host to Inventory and update ssh keys
  hosts: "{{ server }}"
  become: true
  vars:
    server: "{{ server }}"
  tasks:
  - name: Add host to Inventory
    add_host:
      name: "{{ new_public_ip }}"
      group: "{{ new_host_group }}"
      ansible_host: "{{ new_public_ip }}"
    vars:
      new_public_ip: "{{ new_public_ip }}"
      new_host_group: "ec2_lists"

- name: Create new group on the new host
  hosts: "{{ new_public_ip }}"
  become: true
  become_user: ec2-user
  vars:
    username: hari
    groupname: hari
    home_directory: /home/hari
  tasks:
  - name: Create group
    group:
      name: "{{ groupname }}"
      state: present
  - name: Create user
    user:
      name: "{{ username }}"
      group: "{{ groupname }}"
      createhome: yes
      home: "{{ home_directory }}"
      shell: /bin/bash
      state: present






