- name: Add host to Inventory and update ssh keys
  hosts: "{{ server }}"
  become: true
  vars:
    server: "{{ server }}"
    username: nani
    groupname: nani
    home_directory: /home/nani
  tasks:
  - name: Add host to Inventory
    add_host:
      name: "{{ new_public_ip }}"
      group: "{{ new_host_group }}"
      ansible_host: "{{ new_public_ip }}"
    vars:
      new_public_ip: "{{ new_public_ip }}"
      new_host_group: "ec2_lists"
  - name: Create new group on the new host
    hosts: "{{ new_public_ip }}"
    become: true
    tasks:
    - name: Create group
      group:
        name: "{{ groupname }}"
        state: present
    - name: Create user
      user:
        name: "{{ username }}"
        group: "{{ groupname }}"
        createhome: yes
        home: "{{ home_directory }}"
        shell: /bin/bash
        state: present
  # - name: Copy id_rsa.pub to remote host
#   copy:
#     src: /home/nani/.ssh/id_rsa.pub
#     dest: /home/nani/.ssh/authorized_keys
#     mode: 0600






