- name: Install Packages on the new Server
  hosts: "{{ new_public_ip }}"
  become: true
  vars:
    new_public_ip: "{{ new_public_ip }}"
  tasks:
  - name: Update all packages to their latest version
    yum:
      name: "*"
      state: latest
  - name: Install Java 17
    yum:
      name: java-17-amazon-corretto-devel
      state: present
  - name: Update bashrc to export Java variables
    blockinfile:
      path: ~/.bashrc
      marker: "# {mark} ANSIBLE MANAGED BLOCK - JAVA VARIABLES"
      block: |
        export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto
        export PATH=$JAVA_HOME/bin:$PATH
    notify: Reload bashrc
  - name: Reload bashrc
    shell: source ~/.bashrc
    args:
      executable: /bin/bash
    when: ansible_check_mode

