---
- name: deploy a cloudformation stack
  hosts: "{{ server }}"
  become: true
  vars:
    server: "{{ server }}"
    stack_name: "{{ stack_name }}"
    region: "{{ region }}"
    template: "{{ template }}"
    UserID: "{{ UserID }}"
    InstanceName: "{{ InstanceName }}"
    InstanceType: "{{ InstanceType }}"
    SecurityGroupIds: "{{ SecurityGroupIds }}"
    ImageID: "{{ ImageID }}"
    SubnetID: "{{ SubnetID }}"
    #cf: "{{ stack_info.cloudformation }}.{{ stack_name }}"
  tasks:
  - name: create cloudformation stack {{ stack_name }}
    amazon.aws.cloudformation:
      stack_name: "{{ stack_name }}"
      state: present
      region: "{{ region }}"
      disable_rollback: true
      template: "{{ template }}"
      template_parameters:
        UserID: "{{ UserID }}"
        InstanceName: "{{ InstanceName }}"
        InstanceType: "{{ InstanceType }}"
        SecurityGroupIds: "{{ SecurityGroupIds }}"
        ImageID: "{{ ImageID }}"
        SubnetID: "{{ SubnetID }}"
      tags:
        StackName: "{{ stack_name }}"
  - name: Get CloudFormation Stack Outputs
    amazon.aws.cloudformation_info:
      stack_name: "{{ stack_name }}"
    - set_fact: cf_out="{{ stack_info.cloudformation | from_json | json_query('stack_outputs') }}"
    #register: stack_info
  - name: Print Stack Outputs
    debug: 
      var: cf_out
      #msg: "Stack Output: {{ item }}"
    #loop: "{{ stack_info.stacks[0].outputs }}"
    #when: stack_info.stacks | length > 0
