---
- name: deploy a cloudformation stack
  hosts: "{{ server }}"
  become: true
  vars:
    server: "{{ server }}"
    stack_name: "{{ stack_name }}"
    region: "{{ region }}"
    template: "{{ template }}"
    UserID: "{{ UserID }}"
    InstanceName: "{{ InstanceName }}"
    InstanceType: "{{ InstanceType }}"
    SecurityGroupIds: "{{ SecurityGroupIds }}"
    ImageID: "{{ ImageID }}"
    SubnetID: "{{ SubnetID }}"
  tasks:
  - name: create cloudformation stack {{ stack_name }}
    amazon.aws.cloudformation:
      stack_name: "{{ stack_name }}"
      state: present
      region: "{{ region }}"
      disable_rollback: true
      template: "{{ template }}"
      template_parameters:
        UserID: "{{ UserID }}"
        InstanceName: "{{ InstanceName }}"
        InstanceType: "{{ InstanceType }}"
        SecurityGroupIds: "{{ SecurityGroupIds }}"
        ImageID: "{{ ImageID }}"
        SubnetID: "{{ SubnetID }}"
      tags:
        StackName: "{{ stack_name }}"
  - name: Get CloudFormation Stack Outputs
    amazon.aws.cloudformation_info:
      stack_name: "{{ stack_name }}"
    set_fact:
        stack_outputs: "{{ cf.cloudformation['nani-ec2-stack-162384'] }}"
    register: cf
  - name: Print Stack Outputs
    debug: 
      var: cf.stack_outputs
      #msg: "Stack Output: {{ item }}"
    #loop: "{{ stack_info.stacks[0].outputs }}"
    #when: stack_info.stacks | length > 0
