- name: Configure disk and partitions
  hosts: "{{ new_public_ip }}"
  become: yes
  vars:
    new_public_ip: "{{ new_public_ip }}"
  tasks:
  - name: Create root logical volume
    lvol:
      vg: vgroot
      lv: lvroot
      size: 4g

  - name: Format root logical volume
    filesystem:
      fstype: ext4
      dev: /dev/mapper/vgroot-lvroot

  - name: Mount root logical volume
    mount:
      path: /
      src: /dev/mapper/vgroot-lvroot
      fstype: ext4
      state: mounted

  - name: Create var logical volume
    lvol:
      vg: vgroot
      lv: lvvar
      size: 1g

  - name: Format var logical volume
    filesystem:
      fstype: ext4
      dev: /dev/mapper/vgroot-lvvar

  - name: Mount var logical volume
    mount:
      path: /var
      src: /dev/mapper/vgroot-lvvar
      fstype: ext4
      state: mounted

  - name: Create tmp logical volume
    lvol:
      vg: vgroot
      lv: lvtmp
      size: 1g

  - name: Format tmp logical volume
    filesystem:
      fstype: ext4
      dev: /dev/mapper/vgroot-lvtmp

  - name: Mount tmp logical volume
    mount:
      path: /tmp
      src: /dev/mapper/vgroot-lvtmp
      fstype: ext4
      state: mounted
