- name: Create LVM with 100% of EBS volume and mount it
  hosts: "{{ new_public_ip }}"
  become: true
  vars:
    new_public_ip: "{{ new_public_ip }}"
  tasks:
  - name: Initialize the EBS volume as a physical volume (PV)
    command: pvcreate /dev/xvdf
    ignore_errors: yes
  - name: Create a new volume group (VG) using the PV
    command: vgcreate vgapp /dev/xvdf
    ignore_errors: yes
  - name: Create a logical volume (LV) that uses 100% of the free space in the volume group
    command: lvcreate -n lvapp -l 100%FREE /dev/vgapp
    ignore_errors: yes
  - name: Create the mount directory
    become: yes
    file:
      path: /app
      state: directory
      mode: "0755"
  - name: Create a file system on the logical volume
    command: mkfs.xfs /dev/vgapp/lvapp
  - name: Mount the logical volume to the directory
    become: yes
    mount:
      path: /app
      src: /dev/vgapp/lvapp
      fstype: xfs
      state: mounted
