- name: Create LVM partition and mount
  hosts: "{{ new_public_ip }}"
  become: yes
  vars:
    new_public_ip: "{{ new_public_ip }}"
  tasks:
  - name: Create partition table
    parted:
      device: /dev/xvda
      number: 1
      state: present
      label: gpt

  - name: Create root partition
    parted:
      device: /dev/xvda
      number: 1
      state: present
      part_end: 6GB

  - name: Create var partition
    parted:
      device: /dev/xvda
      number: 2
      state: present
      part_start: 6GB
      part_end: 8GB

  - name: Format root partition
    filesystem:
      fstype: ext4
      dev: "/dev/xvda1"

  - name: Format var partition
    filesystem:
      fstype: ext4
      dev: "/dev/xvda2"

  - name: Mount root partition
    mount:
      path: /
      src: "/dev/xvda1"
      fstype: ext4
      state: mounted

  - name: Mount var partition
    mount:
      path: /var
      src: "/dev/xvda2"
      fstype: ext4
      state: mounted
